apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx2
    tag: alpine2
  name: nginx-alpine2
  namespace: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx2
      tag: alpine2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx2
        tag: alpine2
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: nginx-alpine2
