apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx2
    tag: alpine2
  name: nginx-alpine2
  namespace: demo
spec:
  ports:
  - port: 8111
    protocol: TCP
    targetPort: 8111
  selector:
    app: nginx2
    tag: alpine2
  type: ClusterIP
